### ISSUE TITLE
program not found !! when importing gmx

### ISSUE THREAD

**Issue by chr7stos** [samuelmurail/gromacs_py#21]
I have installed gromacs_py (using pip because conda installation could not work) on an anaconda python 3.8 environment and I get: `program not found !!` when trying `from gromacs_py import gmx`. 

`program not found !!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/gromacs_py/gmx/__init__.py", line 11, in <module>
    from .topsys import TopSys
  File "/opt/anaconda3/lib/python3.8/site-packages/gromacs_py/gmx/topsys.py", line 38, in <module>
    GMX_BIN = os_command.which('gmx')
  File "/opt/anaconda3/lib/python3.8/site-packages/os_command_py/os_command.py", line 56, in which
    raise IOError("program not found :", program_list)
OSError: [Errno program not found :] ('gmx',)`

**Comment by samuelmurail** [comment]
You need to install gromacs. If you have already installed it, add the `gmx` location in your `$PATH`.
I'll suggest you create a conda env, to have all software dependencies (gromacs, rdkit, ambertools):

```
cd gromacs_py
conda env create -f .conda.yml
conda activate gromacs_py
python setup.py install
```

**Comment by samuelmurail** [comment]
@chr7stos Did that solve your issue ?

**Comment by chr7stos** [comment]
@samuelmurail thank you, that solved the issue.
